# ~/.config/gtk-3.0/settings.ini
[Settings]
gtk-theme-name=Yaru
gtk-icon-theme-name=Yaru
gtk-application-prefer-dark-theme=true

# ~/.config/gtk-4.0/settings.ini
[Settings]
gtk-icon-theme-name=Yaru
gtk-theme-name=Yaru
